[package]
name = "parcoursup"
version = "0.1.0"
authors = ["Benedikt Becker <benedikt.becker@inria.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
